name: 'Colutius'
description: 'Linux 迷你生态园'
branding:
  icon: 'message-circle'
  color: 'blue'
inputs:
  token:
    required: true
    description: 'telegram bot token'
  chatid:
    required: true
    description: 'telegram chat id'
  message:
    required: option
    description: 'send message'
  button:
    required: option
    description: 'link button'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.chatid }}
    - ${{ inputs.message }}
    - ${{ inputs.button }}
