name: 'Telegram Msg'
description: 'Send Message To Telegram'
branding:
  icon: 'message-circle'
  color: 'blue'
inputs:
  token:
    required: true
    description: 'telegram bot token'
  chatid:
    required: true
    description: 'telegram chat id'
  message:
    required: option
    description: 'send message'
    default: |
      👇新的提交👇
          
      👤提交人: [${{ github.actor }}]
      
      📄提交信息: ${{ github.event.commits[0].message }}
      
      📦仓库: ${{ github.repository }}
  button:
    required: option
    description: 'enable button'
    default: true
  button_name:
    required: option
    description: 'link button name'
    default: 👀查看更改👀
  button_url:
    required: option
    description: 'link button url'
    default: https://github.com/${{ github.repository }}/commit/${{github.sha}}
  is_notify:
    required: option
    description: 'notify or not '
    default: true
  is_preview:
    required: option
    description: 'web page preview or not '
    default: true
    
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.chatid }}
    - ${{ inputs.message }}
    - ${{ inputs.button }}
    - ${{ inputs.button_name }}
    - ${{ inputs.button_url }}
    - ${{ inputs.is_notify }}
    - ${{ inputs.is_preview }}
