name: hello

on:
  schedule:
  - cron:  '30 15 * * *'
jobs:
  get_comment:
    runs-on: ubuntu-latest
    steps:
    - name: get yiyan
        run: |
          echo "YIYAN=$(curl 'https://v1.hitokoto.cn?c=i' | jq -r .hitokoto)" >> $GITHUB_ENV
    - uses: colutius/Telegram-Msg@main
      with:
        token: ${{ secrets.TELEGRAM_TOKEN }}
        chatid: ${{ secrets.TELEGRAM_TO }}
        button: false
        message: |
          晚安家人们~
          
          🗓每日一言: ${{ env.YIYAN }}
          
